spring:
  #数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
  global-config:
    db-config:
      table-prefix: t_  #设置mybatis-plus的全局配置
      id-type: auto
  type-enums-package: com.cheng.mybatisplus.enums
  type-aliases-package: com.cheng.mybatisplus.pojo

