server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称

  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
     # defaultZone: http://eureka7002.com:7002/eureka/   集群
      defaultZone: http://eureka7001.com:7001/eureka/

  server:
    enable-self-preservation: false   #默认为true，自我保护机制，客户端连接服务中心，默认每30秒发送一个心跳连接，如果超过90秒
                                      #服务中心还没有收到心跳连接，他也不会删除你客户端，他觉得你有可能是网络拥塞。设计思想为宁可保留错误的客户端，也不能删除有可能健康的客户断
