spring:
# ???????
  datasource:
# ???????
    type: com.zaxxer.hikari.HikariDataSource
# ?????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: root
