server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
       - id: payment_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
      #   uri: http://localhost:8001          #匹配后提供服务的路由地址
         uri: lb://CLOUD-PAYMENT-SERVICE
         predicates:
         - Path=/payment/get/**         # 断言，路径相匹配的进行路由

       - id: payment_route2   #路由的id，没有固定规则但要求唯一，建议配合服务吗
        # uri: http://localhost:8001
         uri: lb://CLOUD-PAYMENT-SERVICE
         predicates:
         - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
       #  - After=2022-10-06T22:10:47.482+08:00[Asia/Shanghai]
       #  - Before=2023-10-06T22:10:47.482+08:00[Asia/Shanghai]
       #  - Between=2022-10-06T22:10:47.482+08:00[Asia/Shanghai],2023-10-06T22:10:47.482+08:00[Asia/Shanghai]
       #  - Cookie=username,cheng
       #  - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
       #  - Host=**.zychi.com




eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka